CREATE SCHEMA `burgersDB`;
USE `burgersDB`;

CREATE TABLE `burgers` (
`id` INT NOT NULL AUTO_INCREMENT,
`burger_name` VARCHAR(255) NOT NULL,
`devoured` BOOLEAN DEFAULT FALSE,
`date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`id`)
);